apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-flask-deployment
  labels:
    app: k8s-flask
spec:
  replicas: 3
  selector:
    matchLabels:
      app: k8s-flask
  template:
    metadata:
      labels:
        app: k8s-flask
    spec:
      containers:
      - name: k8s-flask
        image: k8s-flask:1.0
        imagePullPolicy: Never
        ports: 
        - containerPort: 5005
